export const communication = {
  BlankUsername: "Enter Username",
  BlankMobile: "Enter Mobile number",
  BlankPassword: "Enter Password",
  BlankFullName: "Enter Full name",
  InvalidUserNotExists:"The credentials provided are incorrect. Try again",
  IncorrectUsernameOrPassword: "Username or Password is incorrect",
  IncorrectMobileOrPassword: "Mobile or Password is incorrect",
  BlankActivityName:"Enter Activity name",
  IncorrectActivityName:"Enter valid Activity name",
  BlankServiceName:"Enter Service name",
  IncorrectServiceName:"Enter valid Service name",
  BlankUnit1Name:"Enter Unit",
  IncorrectUnit1Name:"Enter valid Unit",
  BlankUnit2Name:"Enter conversion unit",
  IncorrectUnitName:"Enter valid conversion unit",
  NetworkError: "Please check your internet connection",
  InvalidPasswordsMatch:"Passwords do not match",
  InvalidOTP:"Enter a valid OTP",
  InvalidMobileBeforeOTP:"Enter mobile number to get the OTP",
  InvalidMobileNotExists:"Mobile does not exist",
  // InvalidUsername: "Enter a valid username",
  // InvalidFullname: "Enter a valid fullname",
  // InvalidPassowrd: "Enter a valid password",
  // InvalidConfirmPassowrd: "Enter a valid confirm password",
  // InvalidMobileNumber: "Enter a valid mobile number",
  // InvalidOTP: "Enter a valid OTP",
  // InvalidMobileBeforeOTP: "Enter mobile number to get the OTP",
  // InvalidPasswordsMatch: "Passwords do not match",

  // InvalidUserNotExists: "The credentials provided are incorrect. Try again",

  // NetworkError: "Please check your internet connection",
  NoData: "No data found",
};
